gantt
    title JJ's 2027 H1 TBR
    dateFormat YYYY-MM-DD
    axisFormat %d %b
    tickInterval 2week

    section Classics
    a Chess Story            :a11, "2027-01-15", 1w
    Historia de Cronopios y Famas :a12, after a11, 1w
    Rayuela                       :a13, after a12, 4w
    El Hombre Rebelde            :a14, after a13, 2w
    El Amor en Tiempos de Cólera  :a15, after a14, 2.5w
    Demons                        :a16, after a15, 5w
    100 años de Soledad             :a17, after a16, 2.5w

    section Latin American Phase
    Exilio y el Reino :a18, after a17, 1.5w
    La Muerte Feliz       :a19, after a18, 1.5w

    section Stephen King
    IT                           :a20, after a19, 6w

    section Camus Finale
    La Tregua         :a21, after a20, 1w
    Ensayo sobre la ceguera :a22, after a21, 2.5w

    section Final Classics
    El Laberinto de la Soledad    :a23, after a22, 2w