gantt
    title JJ's TBR Mar'26
    dateFormat  YYYY-MM-DD
    axisFormat  %d %b
    tickInterval 1week



    section Classics 2
    East of Eden          :a9, 2026-02-20, 3.6w

    section Book Club
    The Silent Patient         :a10, 2026-03-17, 2w
    Project Hail Mary           :a11, after a10, 2w

    section Camus Finale
    The Rebel                  :a12, after a11, 2w
    Exile and the Kingdom      :a13, after a12, 1w
    A Happy Death              :a14, after a13, 1w

    section Break
    Of Mice and Men             :a15, after a14, 1w

    section Dostoevsky Foundation
    Notes from Underground     :a16, after a15, 1w
    Crime and Punishment       :a17, after a16, 4w
    White Nights               :a18, after a17, 1w
    The Brothers Karamazov     :a19, after a18, 5w
    %% Demons                     :a20, after a19, 5w

    section Red Rising (Books 4-6)
    %%Iron Gold                  :a21, after a20, 2w
    %%Dark Age                   :a22, after a21, 3w
    %%Light Bringer              :a23, after a22, 3w

    section Red God (Projected)
    %%Red God Release (est. late 2026) :milestone, 2026-11-15, 1d