gantt
    title JJ's TBR Mar'26
    dateFormat YYYY-MM-DD
    axisFormat %d %b
    tickInterval 2week

     section Currently Reading
    11/22/63                      :a1, 2026-05-17, 4.5w

    section Step 1: Russian Warm-up
    Master & Margarita                  :a2, after a1, 2w
    White Nights     :a3, after a2, 1w

    section Step 2: First Big Dostoyevsky
    Crime and Punishment          :a4, after a3, 4w

    section Step 3: Palate Cleanser & Mexican Must
    El laberinto de la soledad    :a5, after a4, 2w
    Notes from the Underground    :a6, after a5, 1.5w

    section Step 4: The Goal
    The Brothers Karamazov        :a7, after a6, 5.5w

    section Step 5: Post-Karamazov Reset
    The Road                      :a8, after a7, 1.5w

    section Step 6: The Long Horror Epic
    IT                            :a9, after a8, 5w

    section Step 7: Short Palate Cleanser
    Ficciones                     :a10, after a9, 1.5w

    section Step 8: Arthurian Finale
    The Once and Future King      :a11, after a10, 4.5w

    section Mood Reads (Flexible - after main sequence)
    Of Mice and Men               :a12, after a11, 1w
    La tregua                     :a13, after a12, 1w
    Ensayo sobre la ceguera       :a14, after a13, 2w
    El túnel                      :a15, after a14, 1w
