gantt
    title JJ's 2027 H1 TBR
    dateFormat YYYY-MM-DD
    axisFormat %d %b
    tickInterval 2week

    section Classics
    A Tale of 2 Cities            :a11, "2027-01-15", 3w
    El Hombre Rebelde            :a12, after a11, 1w
    El Amor en Tiempos de Cólera  :a13, after a12, 2.5w
    Demons                        :a14, after a13, 6w
    100 años de Soledad             :a15, after a14, 3w

    section Latin American Phase
    La Tregua                     :a16, after a15, 1w
    Ensayo Sobre la Ceguera       :a17, after a16, 2w

    section Stephen King
    IT                           :a20, after a17, 6w

    section Camus Finale
    Exile and the Kingdom         :a18, after a20, 1w
    A Happy Death                 :a19, after a18, 1w

    section Final Classics
    El Laberinto de la Soledad    :a21, after a19, 2w