gantt
    title JJ's TBR Ago'26
    dateFormat YYYY-MM-DD
    axisFormat %d %b
    tickInterval 2week

    section Currently Reading
    Notes from the Underground    :a6, '2026-10-08', 1w
    The Illustrated Man         :a4, '2026-10-07', 3w

    section Palate Cleanser
    

    section Rest period
    The Book Thief        :a7, after a6, 2.5w
    Ficciones               :a3, after a4, 2w
    Exilio y el Reino          :a2, after a3, 2w

    section End Year Goal
    
    A chess story & otros         :a1, after a2, 1.5w  
    
    section End Year
    
    The Brothers Karamazov:    a8, after a7, 6w
    The Road                      :a9, after a8, 1.5w
    

%% The Book Thief        :a7, after a6, 2w
%%    The Brothers Karamazov:    a9, after a8, 6w
