gantt
    title JJ's TBR Ago'26
    dateFormat YYYY-MM-DD
    axisFormat %d %b
    tickInterval 2week

    section Currently Reading
    Death of Ivan Ilych         :a5, '2026-10-02, 0.5w
    The Illustrated Man         :a4, '2026-10-02, 3w

    section Palate Cleanser
    Notes from the Underground    :a6, after a5, 1w

    section The Goal
    The Brothers Karamazov        :a7, after a6, 6w
    Ficciones               :a3, after a4, 2w
    Exilio y el Reino          :a2, after a3, 2w

    section Post-Karamazov Reset
    The Road                      :a8, after a7, 1.5w
    A chess story & otros         :a1, after a2, 1.5w  
    
    section Restorative Classics
    The Book Thief                        :a9, after a8, 2w
    